### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by matkoniecz** [Whazor/Roundtrip#6]
See https://choosealicense.com/ for tl;dr and to confirmation that it is a real problem

Currently no license is mentioned anywhere, what makes this code fully copyrighted. This is a default for any creative work - what includes software.

Please, please add a license. The fact none is listed makes using this software a legal quagmire.

For start - people are not allowed to make pull requests with improvements as it would require ditribution of modified code - that is fully copyrighted.

For example currently it is not legal to use, improve or distribute this code. Hopefully this is not the intended effect, given that code was open sources.

In case that for some reason not releasing it under open license is intentional - mentioning it in the readme also would be a good idea. Though note that given that it is open sourced it will not stop anyone not caring about copyrights.

Popular licences include:

 - MIT license that allows people to use code for any purpose
 - GNU GPLv3 that intends to allow everything but to block people from distributing closed source versions that build on open source project

Feel free to ask me questions :) I know and understand that people often prefer to ignore copyright law, unfortunately it will not make it disappear.

**Comment by whazor** [comment]
Thanks!

**Comment by matkoniecz** [comment]
And thanks for adding the licence!

**Comment by whazor** [comment]
By the way, currently me and @roconda are working on a new (closed source) version at [Tripchemy.com](https://www.tripchemy.com/KRK/2018-11-15/2018-11-26). We build our own scrapers and algorithms and provide precalculated trips for you :).

**Comment by matkoniecz** [comment]
@Whazor - from quick look at it: as usual with such tools (focused on cheap prices for a trip) one irritating this is that user is expected to specify exact dates.

I understand is that queries like "any date on February" is obnoxious from a performance perspective but even small flexibility may be very useful for at least some users (maybe you already considered it and it turned out to not be worth the effort).
